### ISSUE TITLE
Is the $ necessary

### ISSUE THREAD

**Issue by wkmor1** [johnbaums/jagstools#6]
Lines 122-124 of jagsresults.r

```
if (exact) params <- paste("^", 
                               gsub("\\|", "$|^", params), 
                               "$", sep = "")
```

is the "$" necessary. Its seems to break exact pattern matching?

**Comment by johnbaums** [comment]
@wkmor1: That should only be evaluated when `regex == FALSE` and `exact==TRUE`. When you use `exact==TRUE`, the function expects that you're passing a vector of exact param names (but if the param has dims and you don't specify a particular node, then it should return all nodes corresponding to the param). 

This bit:

``` r
params <- paste0(gsub('(?=\\.|\\[|\\])', '\\1\\\\', params, perl=TRUE),
                     '(\\[.*\\])?', collapse='|')
```

creates a pipe-separated string of sub-patterns, each of which corresponds to one of the param names passed in your vector. 

e.g.

``` r
params <- c('a', 'bbbb', 'c.c[1, 3]', 'dddd[4]')
paste0(gsub('(?=\\.|\\[|\\])', '\\1\\\\', params, perl=TRUE),        
            '(\\[.*\\])?', collapse='|')
## [1] "a(\\[.*\\])?|bbbb(\\[.*\\])?|c\\.c\\[1, 3\\](\\[.*\\])?|dddd\\[4\\](\\[.*\\])?"
```

The bit of code you're talking about should just tack on a `^` at the start of each sub-pattern, and a `$` at the end of each sub-pattern. It _is_ necessary, I think, because without it, we could have:

``` r
params <- 'a'
params <- paste0(gsub('(?=\\.|\\[|\\])', '\\1\\\\', params, perl=TRUE), 
                 '(\\[.*\\])?', collapse='|')
## [1] "a(\\[.*\\])?"
```

Which would match any parameters with an `a` in their name. If we stick the caret to the front, it'll still match any parameters that begin with `a`. Using the `$` at the end as well, it should only match the param of interest:

``` r
grep("^a(\\[.*\\])?$", "a")
## [1] 1
```

Let me know if I'm missing something.

**Comment by johnbaums** [comment]
I'm going to close this - let me know if you still think there's a problem. I'm convinced the `$` was necessary. ;)
